config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :comments
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#welcome'


  resources :clients do
    resources :yoga_classes, only: [:new, :show]
  end

  get 'yoga_classes/thirty_minute_yoga_classes', to: 'yoga_classes#thirty_minute_yoga_classes', as: 'thirty_minute_yoga_classes'
  get 'yoga_classes/fourty_five_minute_yoga_classes', to: 'yoga_classes#fourty_five_minute_yoga_classes', as: 'fourty_five_minute_yoga_classes'
  get 'yoga_classes/sixty_minute_yoga_classes', to: 'yoga_classes#sixty_minute_yoga_classes', as: 'sixty_minute_yoga_classes'

  resources :yoga_classes

  #resources :users do
  #  resources :yoga_classes, only: [:new, :show]
  #end

  get '/yoga_classes/:id/yoga_class_data', to: 'yoga_classes#yoga_class_data'
  get '/users/:id/yoga_classes', to: 'users#yoga_classes'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :org_name, uniqueness: true
  validates :org_name, presence: true
  validates :point_of_contact, presence: true
  validates :email, presence: true
  has_many :yoga_classes#, inverse_of: :client
  has_many :users, through: :yoga_classes
  #accepts_nested_attributes_for :yoga_classes
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :yoga_class
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :yoga_classes
  has_many :clients, through: :yoga_classes
  has_many :comments
  validates :email, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    # If you are using confirmable and the provider(s) you use validate emails,
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
   end
  end
end

app/models/yoga_class.rb
class YogaClass < ApplicationRecord
  belongs_to :user#, optional: true
  belongs_to :client #, optional: true#, inverse_of: :yoga_classes
  has_many :comments
  validates :title, presence: true
  validates :class_plan, presence: true

  def self.thirty_minute_yoga_classes
    where("duration = 30")
  end

  def self.fourty_five_minute_yoga_classes
    where("duration = 45")
  end

  def self.sixty_minute_yoga_classes
    where("duration = 60")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def welcome
  end

  # protect_from_forgery with: :exception
  #
  # before_action :configure_permitted_parameters, if: :devise_controller?
  #
  # protected
  # 
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name,:last_name, :email, :password) }
  #   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name,:last_name, :email, :password) }
  # end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    #binding.pry
    if @client.save
      redirect_to @client
    else
      render :new
    end
    end

  def show
    @client = Client.find(params[:id])
  end


  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    @client.update(yoga_class_params)

    if @client.save
     redirect_to @client
    else
      render :edit
    end
  end

  def index
    @clients = Client.all.sort_by {|client| client.org_name}
    render json: @clients
  end

  private

  def client_params
    params.require(:client).permit(:org_name, :point_of_contact, :email)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    #binding.pry
    if @comment.save
        render :json => @comment.as_json(include: :user)
    else
        redirect_to request.referrer
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :yoga_class_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def yoga_classes
    @user = User.find(params[:id])
    render json: @user.yoga_classes
  end
end

app/controllers/yoga_classes_controller.rb
class YogaClassesController < ApplicationController
  before_action :authenticate_user! #test this
  #before_action :set_client

  def thirty_minute_yoga_classes
  end

  def fourty_five_minute_yoga_classes
  end

  def sixty_minute_yoga_classes
  end

  def new
    @yoga_class = current_user.yoga_classes.build(client_id: params[:client_id])
  end

  def create
    @yoga_class = YogaClass.new(yoga_class_params)
    @yoga_class.user = current_user
    #binding.pry
    if @yoga_class.save
      redirect_to @yoga_class
    else
      render :new
    end
    end

  def show
    @yoga_class = YogaClass.find(params[:id])
    @comment = @yoga_class.comments.build
    @comments = @yoga_class.comments.all
  end


  def edit
    @yoga_class = YogaClass.find(params[:id])
  end

  def update
    @yoga_class = YogaClass.find(params[:id])

    @yoga_class.update(yoga_class_params)

    if @yoga_class.save
     redirect_to @yoga_class
    else
      render :edit
    end
  end

  def index
    @yoga_classes = YogaClass.all
    #render json: @yoga_classes
  end

  def yoga_class_data
    @yoga_class = YogaClass.find(params[:id])
    #render json: YogaClassSerializer.serialize(yoga_class)
    render json: @yoga_class
  end


  private

  def yoga_class_params
    params.require(:yoga_class).permit(:notes, :location, :title, :intention, :class_plan, :class_size, :duration, :user_id, :client_id)
  end

  #def set_client
  #  @client = Client.find(params[:client_id])
  #end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/yoga_classes_helper.rb
module YogaClassesHelper
end

app/views/application/welcome.html.erb
<div class="text-center">
<h1>Welcome to the Private Client Tracker!</h1>
<ul>
    <% if user_signed_in? %>
<%= link_to "Create a New Class", new_yoga_class_path %><br>
<%= link_to "View All Classes", yoga_classes_path %><br>
<%= link_to "Create a Client", new_client_path %><br>
<%= link_to "View All Clients", clients_path %><br>
  <%end%>
</ul>
</div>

app/views/clients/_form.html.erb
<% if @client.errors.any? %>
<div id="error_explanation">
  <h3>
    <%= pluralize(@client.errors.count, "error") %>
    prohibited this post from being saved:
  </h3>

  <ul>
  <% @client.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for @client do |f| %>


  <label>Name of Orginization:</label><br>
  <%= f.text_field :org_name %><br>

  <label>Point of Contact:</label><br>
  <%= f.text_field :point_of_contact %><br>

  <%= f.label :email %><br>
  <%= f.text_field :email %><br>

  <%= f.submit "Submit" %>
 <% end %>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= render 'form' %>

app/views/clients/index.html.erb
<h1>List of All Clients</h1>
<p><%= link_to "Create a Client", new_client_path %><br></p>

<% @clients.each do |client| %>
<h3>              <%= link_to client.org_name, client_path(client) %></h3>
<%end%>

app/views/clients/new.html.erb
<h1>Create a New Client</h1>

<%= render 'form' %>

app/views/clients/show.html.erb
<h1><%=@client.org_name%></h1>
<label>Point of Contact: </label><%=@client.point_of_contact%> <br>
<label><%=@client.point_of_contact%>'s email: </label><%=@client.email%>

<br>
<p>History of Classes:</p>
<% @client.yoga_classes.each do |yoga_class| %>
<ul>
  <li><%= link_to yoga_class.title, client_yoga_class_path(@client, yoga_class)%></li>
</ul>
<% end %>

<br>
<h2>Create a new Yoga Class</h2>
<%= link_to "New Yoga Class", new_client_yoga_class_path(@client) %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

  <label>Comment:</label><br>
  <%= f.text_area :content %><br>
  <%= f.hidden_field(:yoga_class_id, :value => comment.yoga_class_id) %>
  <%= f.submit "Submit", data: { disable_with: false } %>
<%end%>

app/views/layouts/_nav.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <% if !user_signed_in? %>
    <li> <%= link_to 'Signup', new_user_registration_path %></li>
    <li> <%= link_to 'Login', new_user_session_path %></li>
    <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
    <% else %>
    <li> <%= link_to 'Logout', destroy_user_session_path, method: "delete"  %></li>
    <%end%>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateClientTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |user| %>
<h3>              <%= link_to user.email, user_path(user) %></h3>
<%end%>

app/views/users/show.html.erb
<h2><%= @user.first_name%> <%= @user.last_name%>'s Profile</h2>
<p>Email Address: <%= @user.email%></p>
<button class="js-yoga-classes" data-id="<%= @user.id %>">View History of Yoga Classes</button>

<div id="user-yoga-classes-<%= @user.id %>">
  <div id="user-yoga-classes-comments-<%= @user.id %>">
  </div>
</div>

app/views/yoga_classes/_form.html.erb
<% if @yoga_class.errors.any? %>
<div id="error_explanation">
  <h3>
    <%= pluralize(@yoga_class.errors.count, "error") %>
    prohibited this post from being saved:
  </h3>

  <ul>
  <% @yoga_class.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

<%= form_for @yoga_class do |f| %>

  <label>Client:</label><br>
  <%= f.collection_select :client_id, Client.all, :id, :org_name %><br>
  Don't see your client? Create new client <%= link_to 'here:', new_client_path %>
  <br>
  <br>

  <%= f.label :title %>:<br>
  <%= f.text_field :title %><br>

  <%= f.label :location %>:<br>
  <%= f.text_field :location %><br>

  <%= f.label :duration %>: (in minutes)<br>
  <%= f.text_field :duration %><br>

  <%= f.label :intention %>:<br>
  <%= f.text_field :intention %><br>

  <%= f.label :class_plan %>:<br>
  <%= f.text_area :class_plan %><br>

  <%= f.label :class_size %>:<br>
  <%= f.text_field :class_size %><br>

  <%= f.label :notes %>:<br>
  <%= f.text_area :notes %><br>

  <%= f.submit "Submit"%>

 <% end %>

app/views/yoga_classes/_yoga_class.erb
<h3><%= link_to yoga_class.title, yoga_class_path(yoga_class) %></h3> <br>
<div id="body-<%= yoga_class.id %>"></div>
<button class="js-more" data-id="<%= yoga_class.id %>">View Class Plan</button>

app/views/yoga_classes/edit.html.erb
<h1>Edit Class</h1>

<%= render 'form' %>

app/views/yoga_classes/fourty_five_minute_yoga_classes.html.erb
<h1> List of 45 Minute Classes </h1>

<% YogaClass.all.fourty_five_minute_yoga_classes.each do |yoga_class|%>
<%= link_to yoga_class.title, yoga_class_path(yoga_class) %> <br>
<%end%>

app/views/yoga_classes/index.html.erb
<h1>List of All Yoga Classes</h1>
<h4>Quick Search </h4>
<%= link_to "30 minute classes", thirty_minute_yoga_classes_path%>
<%= link_to "45 minute classes", fourty_five_minute_yoga_classes_path%>
<%= link_to "60 minute classes", sixty_minute_yoga_classes_path%><br>

<p><%= link_to "Create a New Class", new_yoga_class_path %><br></p>

<% @yoga_classes.each do |yoga_class| %>
  <%= render partial: "yoga_class", locals: {yoga_class: yoga_class} %>
<%end%>

app/views/yoga_classes/new.html.erb
<h1>Create a new Class</h1>

<%= render 'form' %>

app/views/yoga_classes/show.html.erb
<h1 class="yogaClassTitle"><%= @yoga_class.title %></h1> <br>

<!--- <a href="#" class="js-next" data-id="<@yoga_class.id%>">Next...</a><br> --->

<label>Duration:</label>
<p class="yogaClassDuration" ><%= @yoga_class.duration %> minutes</p>

<label>Location:</label>
<p class="yogaClassLocation"><%= @yoga_class.location %></p>

<label>Intention:</label>
<p class="yogaClassIntention"><%= @yoga_class.intention %></p>

<label>Class Plan:</label>
<p class="yogaClassClassPlan"><%= @yoga_class.class_plan %></p>

<label>Class Size:</label>
<p class="yogaClassSize"><%= @yoga_class.class_size %></p>

<label>Notes:</label>
<p class="yogaClassNotes"><%= @yoga_class.notes %></p>

<label>Teacher:</label>
<p class="yogaTeacher"><%= @yoga_class.user.email %></p>


<p>Comments</p>
<div class="comment-content">
<% @comments.each do |comment| %>
    <strong><%= comment.user.first_name%> <%=comment.user.last_name%> said </strong>
    <br>
    <p><%= comment.content %></p>
<% end %>
</div>

<%= render partial: 'comments/form', locals: {comment: @comment} %>

app/views/yoga_classes/sixty_minute_yoga_classes.html.erb
<h1> List of 60 Minute Classes </h1>

<% YogaClass.all.sixty_minute_yoga_classes.each do |yoga_class|%>
<%= link_to yoga_class.title, yoga_class_path(yoga_class) %> <br>
<%end%>

app/views/yoga_classes/thirty_minute_yoga_classes.html.erb
<h1> List of 30 Minute Classes </h1>

<% YogaClass.all.thirty_minute_yoga_classes.each do |yoga_class|%>
<%= link_to yoga_class.title, yoga_class_path(yoga_class) %> <br>
<%end%>